In [1]:
import gym_2048
import gym
import numpy as np
import random
import copy

from itertools import permutations
from collections import Counter

import copy
import random
import math
from timeit import default_timer as timer

In [2]:
import copy
import random
import math


def numberofzeroes(bb):
    count = 0
    b = copy.deepcopy(bb)

    for i in range(4):
        for j in range(4):
            if b[i][j] == 0:
                count = count + 1
    return 2**count


def calculate(board1):
    b = copy.deepcopy(board1)
    sum = 0
    for i in range(3):
        for j in range(3):
            sum = sum + b[i][j] * boardm[i][j]
    return sum


def is_done(bb):
    b = copy.deepcopy(bb)

    if b == push_down(b)[0] and b == push_up(b)[0] and b == push_left(b)[0] and b == push_right(b)[0]:
        return True
    else:
        return False


def print_board(bb):
    b = copy.deepcopy(bb)
    for i in b:
        print(i)


def find_zeros(bb):
    b = copy.deepcopy(bb)
    list = []
    for i in range(4):
        for j in range(4):
            if b[i][j] == 0:
                list.append((i, j))
    return list


def pick_random_place(bb):
    b = copy.deepcopy(bb)
    list = find_zeros(b)
    return random.choice(list)


def place_random(bb):
    b = copy.deepcopy(bb)
    picked_location = pick_random_place(b)
    q = random.randint(0, 100)
    f=2 #since i am checking only for 2 as min
    # if q < 80:

    #     f = 2
    # else:
    #     f = 4

    b[picked_location[0]][picked_location[1]] = f
    return b


def push_up(bb):
    s = 0

    b = copy.deepcopy(bb)
    b_new = copy.deepcopy(bb)

    for i in [0, 1, 2, 3]:
        l = []
        for j in range(0, 4):
            l.append(b[j][i])

        l = list(filter((0).__ne__, l))

        l_n = []
        while len(l) > 1:
            if l[0] == l[1]:
                l_n.append(2 * l[0])
                s = s + (2 * l[0])
                l.pop(0)
                l.pop(0)

            else:
                l_n.append(l[0])
                l.pop(0)
        if len(l) == 1:
            l_n.append(l[0])
            l.pop(0)

        for k in range(4 - len(l_n)):
            l_n.append(0)

        for j in range(0, 4):
            b_new[j][i] = l_n[j]
    return b_new, s


def push_down(bb):
    s = 0

    b = copy.deepcopy(bb)
    b_new = copy.deepcopy(bb)

    for i in [0, 1, 2, 3]:
        l = []
        for j in [3, 2, 1, 0]:
            l.append(b[j][i])

        l = list(filter((0).__ne__, l))

        l_n = []
        while len(l) > 1:
            if l[0] == l[1]:
                l_n.append(2 * l[0])
                s = s + (2 * l[0])
                l.pop(0)
                l.pop(0)

            else:
                l_n.append(l[0])
                l.pop(0)
        if len(l) == 1:
            l_n.append(l[0])
            l.pop(0)

        for k in range(4 - len(l_n)):
            l_n.append(0)

        for j in range(0, 4):
            b_new[j][i] = l_n[3 - j]
    return b_new, s


def push_left(bb):
    s = 0

    b = copy.deepcopy(bb)
    b_new = copy.deepcopy(bb)

    for i in [0, 1, 2, 3]:
        l = []
        for j in [0, 1, 2, 3]:
            l.append(b[i][j])

        l = list(filter((0).__ne__, l))

        l_n = []
        while len(l) > 1:
            if l[0] == l[1]:
                l_n.append(2 * l[0])
                s = s + (2 * l[0])
                l.pop(0)
                l.pop(0)

            else:
                l_n.append(l[0])
                l.pop(0)
        if len(l) == 1:
            l_n.append(l[0])
            l.pop(0)

        for k in range(4 - len(l_n)):
            l_n.append(0)

        for j in range(0, 4):
            b_new[i][j] = l_n[j]

    return b_new, s


def push_right(bb):
    s = 0

    b = copy.deepcopy(bb)
    b_new = copy.deepcopy(bb)

    for i in [0, 1, 2, 3]:
        l = []
        for j in [3, 2, 1, 0]:
            l.append(b[i][j])

        l = list(filter((0).__ne__, l))

        l_n = []
        while len(l) > 1:
            if l[0] == l[1]:
                l_n.append(2 * l[0])
                s = s + (2 * l[0])
                l.pop(0)
                l.pop(0)
            else:
                l_n.append(l[0])
                l.pop(0)
        if len(l) == 1:
            l_n.append(l[0])
            l.pop(0)

        for k in range(4 - len(l_n)):
            l_n.append(0)

        for j in range(0, 4):
            b_new[i][j] = l_n[3 - j]

    return b_new, s


def max1(b):
    l=b[0][0]
    for i in range(4):
        for j in range(4):
            if b[i][j]>l:
                l=b[i][j]
    return l

def minimax(board, is_maximising, depth, alpha, beta, score, action, max_depth):
    # print("depth:", depth, score)
    # print_board(board)

    if is_done(board):
        return score, 0, action

    if depth == max_depth:
        # print("Depth Reached", depth)
        return (numberofzeroes(board) + calculate(board)), 0, action

    if is_maximising:

        # print("\n\n***Max")

        actions = ['up', 'down', 'left', 'right']

        best = -math.inf
        best_move = actions[0]

        for i in actions:
            temp_board = []
            temp_board = copy.deepcopy(board)
            # print("\nAction", i)

            if i == 'left':
                result = push_left(temp_board)

            elif i == 'right':
                result = push_right(temp_board)

            elif i == 'up':
                result = push_up(temp_board)

            elif i == 'down':
                result = push_down(temp_board)

            if result[0] != board:
                temp_board = copy.deepcopy(result[0])
                # print_board(temp_board)

                return_value = minimax(temp_board, False, depth + 1, alpha, beta, (result[1] * numberofzeroes(temp_board) * calculate(board)), action + " " + i, max_depth)
                if best < return_value[0]:
                    # print("Return at Max: ", return_value[0], best, i, "Depth:", depth)
                    # print("Replacing at Max with", return_value[0], best)
                    best = return_value[0]
                    best_move = i
                # alpha = max(alpha, best)
                # if beta <= alpha:
                #     return score, best_move, action
                if alpha < best:
                    alpha = best
                if beta <= alpha:
                    break
        return best, best_move, action

    else:
        empty = find_zeros(board)
        # print(empty)

        if len(empty) == 0:
            return score, 0

        # print("\n\n***Min")
        best_min = +math.inf
        best_min_move = empty[0]

        for i in empty:
            temp_board = copy.deepcopy(board)
            temp_board[i[0]][i[1]] = 2
            return_value = minimax(temp_board, True, depth + 1, alpha, beta, (numberofzeroes(temp_board) * calculate(temp_board)), action, max_depth)
            # print("Return at Min: ", return_value)
            if best_min > return_value[0]:
                # print("Replacing at Min with", return_value[0], best_min)
                best_min = return_value[0]
                best_min_move = i
            # beta = min(beta, best_min)
            # if beta <= alpha:
            #     return score, best_min_move, action

            if beta > best_min:
                beta = best_min
            if beta <= alpha:
                break

        return best_min, best_min_move

In [3]:
dump = []

In [4]:
for i in range(10):
    boardm = [[4 ** 15, 4 ** 14, 4 ** 13, 4 ** 12],
              [4 ** 8, 4 ** 9, 4 ** 10, 4 ** 11],
              [4 ** 7, 4 ** 6, 4 ** 5, 4 ** 4],
              [4 ** 0, 4 ** 1, 4 ** 2, 4 ** 3]]

    board = [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
    score1 = 0
    board = place_random(board)
    
    print("\n")

    print_board(board)


    score = 0

    max_depth = 2

    # t = minimax(board, True, 0, -1, +1, score, "", max_depth)
    # print(t)
    arr=[]
    ss=[]

    board = [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
    score1 = 0
    choices = [2, 4]
    score = 0

    max_depth = 3

    board = place_random(board)
    while not is_done(board):
        t = minimax(board, True, 0, float("-inf"), float("inf"), score, "", max_depth)[1]
        # print("\nFinal Action:", t) kar dena
        if t == 'left':
            result = push_left(board)
            act=[0,0,0,1]

        elif t == 'right':
            act=[0,1,0,0]
            result = push_right(board)

        elif t == 'up':
            act=[1,0,0,0]
            result = push_up(board)

        elif t == 'down':
            act=[0,0,1,0]
            result = push_down(board)

        if result[0] != board:
            board = copy.deepcopy(result[0])
            # print_board(board) kar dena
            score1 = score1 + result[1]
            score = result[1] * numberofzeroes(board) * calculate(board)
            newspace=[]
            for m in range(4):
                for n in range(4):
                    newspace.append(result[0][m][n])
            dump.append((newspace, int(score/1000000000000), act))
            # print("\n") kar dena
            # print("=" * 20) kar dena
            # print("score", score1)kar dena
            # print("Final----")kar dena
            board = place_random(board)
    #         print_board(board)
    #         print(dump)
    #         print()
    #     print(score1)
        ss.append(score)
        s=max1(board)
        arr.append(s)
    print("\n")
    print_board(board)



[0, 0, 0, 0]
[0, 0, 0, 2]
[0, 0, 0, 0]
[0, 0, 0, 0]


[128, 4, 256, 2]
[32, 512, 128, 4]
[4, 64, 16, 2]
[2, 8, 2, 4]


[0, 0, 0, 0]
[2, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]


[256, 512, 256, 2]
[32, 64, 128, 4]
[8, 32, 16, 32]
[4, 2, 8, 2]


[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 2, 0, 0]


[2048, 1024, 512, 2]
[4, 64, 128, 4]
[32, 16, 8, 2]
[2, 4, 2, 32]


[2, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]


[1024, 512, 32, 8]
[64, 128, 256, 16]
[4, 64, 32, 4]
[2, 8, 4, 2]


[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 2, 0, 0]


[128, 16, 8, 2]
[2, 64, 2048, 4]
[256, 32, 16, 8]
[16, 4, 32, 2]


[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 2, 0]


[1024, 512, 64, 16]
[32, 128, 256, 8]
[4, 16, 32, 4]
[2, 8, 4, 2]


[0, 0, 0, 0]
[0, 0, 2, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]


[2048, 512, 8, 2]
[2, 128, 256, 32]
[16, 4, 16, 4]
[2, 8, 4, 2]


[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 2, 0]


[1024, 512, 32, 2]
[32, 128, 256, 4]
[8, 64, 16, 8]
[4, 8, 4, 2]


[0, 2, 0, 0]
[0, 0, 0, 0]
[0, 

In [5]:
# dump=[]

In [6]:
len(dump)

12740

In [7]:
dump

[([2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0, [0, 0, 0, 1]),
 ([2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0, [1, 0, 0, 0]),
 ([2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0, [1, 0, 0, 0]),
 ([2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0, [1, 0, 0, 0]),
 ([4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0], 351, [0, 0, 0, 1]),
 ([4, 4, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0, [1, 0, 0, 0]),
 ([4, 4, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0, [1, 0, 0, 0]),
 ([0, 0, 8, 4, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0], 70, [0, 1, 0, 0]),
 ([8, 4, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0], 0, [0, 0, 0, 1]),
 ([8, 4, 0, 2, 4, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0], 0, [1, 0, 0, 0]),
 ([8, 4, 2, 2, 4, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0], 0, [1, 0, 0, 0]),
 ([8, 4, 4, 0, 4, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0], 40, [0, 0, 0, 1]),
 ([8, 8, 0, 0, 4, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0], 87, [0, 0, 0, 1]),
 ([16, 2, 0, 0, 4, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0], 290, [0, 0, 0, 1]),
 ([16, 4, 0,

In [8]:
import os
os.environ['KERAS_BACKEND'] = 'theano'

from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import np_utils

import numpy
import pandas as pd
import theano

Using Theano backend.


In [9]:
model = Sequential()

model.add(Dense(100, input_dim=16, activation='relu'))
model.add(Dense(100, activation='relu'))
# model.add(Dense(50, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(4, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [20]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 100)               1700      
_________________________________________________________________
dense_2 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1010      
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 44        
Total params: 12,854
Trainable params: 12,854
Non-trainable params: 0
_________________________________________________________________


In [10]:
def get_vectors(dump):
    d = np.array(dump)
    l=d[:,0]
    x=list(l)
    x = np.array(x)
    p = d[:,2]
    y = list(p)
    y = np.array(y)
    return x, y

In [11]:
x, y = get_vectors(dump)

In [12]:
model.fit(x, y, epochs=200)

Epoch 1/200
12740/12740 [==============================] - 0s 28us/step - loss: 1.9887 - acc: 0.4560
Epoch 2/200
12740/12740 [==============================] - 0s 29us/step - loss: 1.2059 - acc: 0.4834
Epoch 3/200
12740/12740 [==============================] - 1s 40us/step - loss: 1.1577 - acc: 0.4834
Epoch 4/200
12740/12740 [==============================] - 0s 38us/step - loss: 1.1333 - acc: 0.4834
Epoch 5/200
12740/12740 [==============================] - 0s 33us/step - loss: 1.1236 - acc: 0.4837
Epoch 6/200
12740/12740 [==============================] - 0s 35us/step - loss: 1.1152 - acc: 0.4837
Epoch 7/200
12740/12740 [==============================] - 0s 34us/step - loss: 1.1092 - acc: 0.4837
Epoch 8/200
12740/12740 [==============================] - 0s 31us/step - loss: 1.1136 - acc: 0.4842
Epoch 9/200
12740/12740 [==============================] - 0s 31us/step - loss: 1.1018 - acc: 0.4841
Epoch 10/200
12740/12740 [==============================] - 0s 36us/step - loss: 1.0997 - a

12740/12740 [==============================] - 0s 32us/step - loss: 1.0616 - acc: 0.4988
Epoch 82/200
12740/12740 [==============================] - 0s 33us/step - loss: 1.0637 - acc: 0.4938
Epoch 83/200
12740/12740 [==============================] - 0s 34us/step - loss: 1.0664 - acc: 0.4935
Epoch 84/200
12740/12740 [==============================] - 0s 33us/step - loss: 1.0674 - acc: 0.4931
Epoch 85/200
12740/12740 [==============================] - 0s 33us/step - loss: 1.0672 - acc: 0.4944
Epoch 86/200
12740/12740 [==============================] - 0s 34us/step - loss: 1.0650 - acc: 0.4958
Epoch 87/200
12740/12740 [==============================] - 0s 33us/step - loss: 1.0720 - acc: 0.4967
Epoch 88/200
12740/12740 [==============================] - 0s 32us/step - loss: 1.0594 - acc: 0.4956
Epoch 89/200
12740/12740 [==============================] - 0s 32us/step - loss: 1.0510 - acc: 0.4978
Epoch 90/200
12740/12740 [==============================] - 0s 33us/step - loss: 1.0535 - acc: 

12740/12740 [==============================] - 0s 30us/step - loss: 0.6381 - acc: 0.7268
Epoch 161/200
12740/12740 [==============================] - 0s 30us/step - loss: 0.6170 - acc: 0.7322
Epoch 162/200
12740/12740 [==============================] - 0s 31us/step - loss: 0.5823 - acc: 0.7506
Epoch 163/200
12740/12740 [==============================] - 0s 30us/step - loss: 0.5649 - acc: 0.7653
Epoch 164/200
12740/12740 [==============================] - 0s 30us/step - loss: 0.5688 - acc: 0.7641
Epoch 165/200
12740/12740 [==============================] - 0s 30us/step - loss: 0.5560 - acc: 0.7662
Epoch 166/200
12740/12740 [==============================] - 0s 29us/step - loss: 0.5460 - acc: 0.7711
Epoch 167/200
12740/12740 [==============================] - 0s 30us/step - loss: 0.5427 - acc: 0.7711
Epoch 168/200
12740/12740 [==============================] - 0s 30us/step - loss: 0.5472 - acc: 0.7709
Epoch 169/200
12740/12740 [==============================] - 0s 29us/step - loss: 0.554

In [21]:
# y_dash = model.predict(x.reshape(len(x),16))

In [14]:
# import keras.utils

In [15]:
# y_dash

In [16]:
# np.argmax(y_dash, axis=1)

In [17]:
env = gym.make('2048-v0')
env.reset()

In [18]:
counter = 0

explore_rate = 0.05

for iteration in range(10):

    env.reset()

    action = env.action_space.sample()
    observation, reward, done, _ = env.step(action + 1)


    while True:
#         env.render()

        counter += 1

        rand_action = env.action_space.sample()

        max_action = np.argmax(model.predict(np.ravel(np.array(list(observation))).reshape(1,16)), axis=1)[0]

        action = int(np.random.choice([rand_action, max_action], 1, p=[explore_rate, 1 - explore_rate]))

#         print("\nAction",action)

        observation, reward, done, _ = env.step(action + 1)

        if done:
            print("\nIteration : ", iteration)
            print(observation)
            break


Iteration :  0
[[  4   8  16   2]
 [  2   4   2  16]
 [  4   8  32 128]
 [  2   4   8  32]]

Iteration :  1
[[  2   4   8   2]
 [  4   8  16   4]
 [  8  16  64  16]
 [ 32  64 128  32]]

Iteration :  2
[[  4   2  16 128]
 [  2   4   8  32]
 [  4   8  64 128]
 [  2   4  16  64]]

Iteration :  3
[[ 4  2  8 16]
 [ 2  4 16 32]
 [ 4 16  2  4]
 [ 8  2  4 16]]

Iteration :  4
[[ 4  2  4  2]
 [ 8  4  2  4]
 [16  8  4  8]
 [64 32 16  4]]

Iteration :  5
[[ 2  8  4  2]
 [ 4  2  8  4]
 [ 8 32  4  8]
 [ 2  8 32 16]]

Iteration :  6
[[ 4  2  4 16]
 [ 2  4 16  4]
 [ 4 16  2 16]
 [ 2  4 16 64]]

Iteration :  7
[[ 4  8 16  2]
 [ 8 16 32 64]
 [ 4 32 64 16]
 [ 2  8 16 32]]

Iteration :  8
[[  2   4   8   4]
 [  8  16  32   8]
 [ 32 128   4  16]
 [  2  64   8   4]]

Iteration :  9
[[  2   4   8  64]
 [  4   8  16   4]
 [  8  16  32 128]
 [  2   4  16  32]]
